### ISSUE TITLE
To do: title with embedded website below

### ISSUE THREAD

**Issue by EstherDeLoof** [OpenWebslides/ICT-Lerarenopleiding#10]
We would like to have a few slides with a title above and a website embedded below (for the padlet and mentimeter questions, to show the login above the embedded site). Is there an elegant way to do that?

**Comment by RubenVerborgh** [comment]
I'd make a slide as follows:

``` HTML
<h2>Title</h2>
<iframe src="…"></iframe>
```

and then make a CSS rule along the lines of

``` CSS
iframe {
    width: 900px;
    height: 400px;
}
```
